apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dash
  name: dash
spec:
  type: NodePort
  ports:
    - name: "8050"
      port: 8050
      targetPort: 8050
  selector:
    app: dash
status:
  loadBalancer: {}
